# Generated by Django 4.1 on 2022-08-17 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=25)),
                ('content', models.CharField(max_length=300)),
                ('postId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_app.newsposts')),
            ],
        ),
    ]
